export const PREDEFINED_TAGS = [
    { id: 0, name: "전체" },
    { id: 1, name: "남자 가수" },
    { id: 2, name: "여자 가수" },
    { id: 3, name: "남자 아이돌" },
    { id: 4, name: "여자 아이돌" },
    { id: 5, name: "케이팝" },
    { id: 6, name: "발라드" },
    { id: 7, name: "힙합" },
    { id: 8, name: "밴드" },
    { id: 9, name: "트로트" },
    { id: 10, name: "인디" },
    { id: 11, name: "OST" },
    { id: 12, name: "70년대" },
    { id: 13, name: "80년대" },
    { id: 14, name: "90년대" },
    { id: 15, name: "00년대" },
    { id: 16, name: "10년대" },
    { id: 17, name: "2020" },
    { id: 18, name: "2021" },
    { id: 19, name: "2022" },
    { id: 20, name: "2023" },
    { id: 21, name: "2024" },
    { id: 22, name: "2025" },
  ];